/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.1.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: 2019年9月2日
 ***********************************************************************************************/

#include "digitaltwin_serializer.h"

//
// Serialize telemetry data
//

bool Battery_SerializeBatteryVoltageTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double batteryVoltage = Battery_Telemetry_ReadBatteryVoltage();

    int neededSize = snprintf(NULL, 0, "%f", batteryVoltage);

    if (neededSize > size - 1)
    {
        LogError("Failed to build batteryVoltage payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", batteryVoltage);
    }

    return true;
}

bool PushButton_SerializeActionNumTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    PUSHBUTTON_ACTIONNUM value = PushButton_Telemetry_ReadActionNum();

    int intValue;
    switch (value)
    {
    case PUSHBUTTON_ACTIONNUM_SingleClick:
        intValue = 1;
        break;

    case PUSHBUTTON_ACTIONNUM_DoubleClick:
        intValue = 2;
        break;

    case PUSHBUTTON_ACTIONNUM_TripleClick:
        intValue = 3;
        break;

    case PUSHBUTTON_ACTIONNUM_LongPress:
        intValue = 10;
        break;

    case PUSHBUTTON_ACTIONNUM_SuperLongPress:
        intValue = 11;
        break;

    default:
        LogError("Invalid actionNum value");
        return false;
    }

    int neededSize = snprintf(NULL, 0, "%d", intValue);
    if (neededSize > size - 1)
    {
        LogError("Failed to build actionNum payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%d", intValue);
    }

    return true;
}

bool PushButton_SerializeMessageTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* message = PushButton_Telemetry_ReadMessage();

    int neededSize = snprintf(NULL, 0, "\"%s\"", message);

    if (neededSize > size - 1)
    {
        LogError("Failed to build message payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", message);
    }

    return true;
}

bool TempHumidSensor_SerializeTemperatureTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double temperature = TempHumidSensor_Telemetry_ReadTemperature();

    int neededSize = snprintf(NULL, 0, "%f", temperature);

    if (neededSize > size - 1)
    {
        LogError("Failed to build temperature payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", temperature);
    }

    return true;
}

bool TempHumidSensor_SerializeHumidityTelemetry(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    double humidity = TempHumidSensor_Telemetry_ReadHumidity();

    int neededSize = snprintf(NULL, 0, "%f", humidity);

    if (neededSize > size - 1)
    {
        LogError("Failed to build humidity payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%f", humidity);
    }

    return true;
}

//
// Serialize read-only property
//

bool DeviceInfo_SerializeManufacturerProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* manufacturer = DeviceInfo_Property_GetManufacturer();

    int neededSize = snprintf(NULL, 0, "\"%s\"", manufacturer);

    if (neededSize > size - 1)
    {
        LogError("Failed to build manufacturer payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", manufacturer);
    }

    return true;
}

bool DeviceInfo_SerializeModelProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* model = DeviceInfo_Property_GetModel();

    int neededSize = snprintf(NULL, 0, "\"%s\"", model);

    if (neededSize > size - 1)
    {
        LogError("Failed to build model payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", model);
    }

    return true;
}

bool DeviceInfo_SerializeSwVersionProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* swVersion = DeviceInfo_Property_GetSwVersion();

    int neededSize = snprintf(NULL, 0, "\"%s\"", swVersion);

    if (neededSize > size - 1)
    {
        LogError("Failed to build swVersion payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", swVersion);
    }

    return true;
}

bool DeviceInfo_SerializeOsNameProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* osName = DeviceInfo_Property_GetOsName();

    int neededSize = snprintf(NULL, 0, "\"%s\"", osName);

    if (neededSize > size - 1)
    {
        LogError("Failed to build osName payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", osName);
    }

    return true;
}

bool DeviceInfo_SerializeProcessorArchitectureProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* processorArchitecture = DeviceInfo_Property_GetProcessorArchitecture();

    int neededSize = snprintf(NULL, 0, "\"%s\"", processorArchitecture);

    if (neededSize > size - 1)
    {
        LogError("Failed to build processorArchitecture payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", processorArchitecture);
    }

    return true;
}

bool DeviceInfo_SerializeProcessorManufacturerProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    char* processorManufacturer = DeviceInfo_Property_GetProcessorManufacturer();

    int neededSize = snprintf(NULL, 0, "\"%s\"", processorManufacturer);

    if (neededSize > size - 1)
    {
        LogError("Failed to build processorManufacturer payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "\"%s\"", processorManufacturer);
    }

    return true;
}

bool DeviceInfo_SerializeTotalStorageProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long totalStorage = DeviceInfo_Property_GetTotalStorage();

    int neededSize = snprintf(NULL, 0, "%ld", totalStorage);

    if (neededSize > size - 1)
    {
        LogError("Failed to build totalStorage payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", totalStorage);
    }

    return true;
}

bool DeviceInfo_SerializeTotalMemoryProperty(char * payloadBuffer, int size)
{
    if (payloadBuffer == NULL)
    {
        return false;
    }

    memset(payloadBuffer, 0, size);

    long totalMemory = DeviceInfo_Property_GetTotalMemory();

    int neededSize = snprintf(NULL, 0, "%ld", totalMemory);

    if (neededSize > size - 1)
    {
        LogError("Failed to build totalMemory payload string");
        return false;
    }
    else
    {
        snprintf(payloadBuffer, size, "%ld", totalMemory);
    }

    return true;
}

