/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.1.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: Sunday, September 8, 2019
 ***********************************************************************************************/

#include "temphumidsensor_interface.h"

#define MAX_MASSAGE_SIZE 256

//
// Application state associated with this interface.
// It contains the DIGITALTWIN_INTERFACE_CLIENT_HANDLE used for responses in callbacks along with properties set
// and representations of the property update and command callbacks invoked on given interface
//
typedef struct TEMPHUMIDSENSOR_INTERFACE_STATE_TAG
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceClientHandle;

} TEMPHUMIDSENSOR_INTERFACE_STATE;

static TEMPHUMIDSENSOR_INTERFACE_STATE appState;

// TempHumidSensorInterface_TelemetryCallback is invoked when a DigitalTwin telemetry message is either successfully delivered to the service or else fails.
static void TempHumidSensorInterface_TelemetryCallback(DIGITALTWIN_CLIENT_RESULT digitalTwinTelemetryStatus, void* userContextCallback)
{
    if (digitalTwinTelemetryStatus == DIGITALTWIN_CLIENT_OK)
    {
        SendTelemetry_Succeeded_Callback("TempHumidSensor", (const char*)userContextCallback);
        LogInfo("TEMPHUMIDSENSOR_INTERFACE: DigitalTwin successfully delivered telemetry message for <%s>", (const char*)userContextCallback);
    }
    else
    {
        SendTelemetry_Error_Callback("TempHumidSensor", (const char*)userContextCallback);
        LogError("TEMPHUMIDSENSOR_INTERFACE: DigitalTwin failed to deliver telemetry message for <%s>, error=<%s> ", (const char*)userContextCallback, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, digitalTwinTelemetryStatus));
    }

    if (strcmp((const char*)userContextCallback, "temperature") == 0)
    {
        ReButton_Digital_Twin_Work_Flag &= ~ReButton_Telemetry_temperature; 
    } 
    else if (strcmp((const char*)userContextCallback, "humidity") == 0)
    {
        ReButton_Digital_Twin_Work_Flag &= ~ReButton_Telemetry_humidity; 
    }
}

// SendTelemetry is a helper function which is periodically invoked by the caller to send telemetry
DIGITALTWIN_CLIENT_RESULT TempHumidSensorInterface_SendTelemetry_Internal(DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle, const char* telemetryName, const char* telemetryData)
{
    DIGITALTWIN_CLIENT_RESULT result;

    result = DigitalTwin_InterfaceClient_SendTelemetryAsync(interfaceHandle, telemetryName, telemetryData,
        TempHumidSensorInterface_TelemetryCallback, (void*)telemetryName);

    if (result != DIGITALTWIN_CLIENT_OK)
    {
        LogError("TEMPHUMIDSENSOR_INTERFACE:: DigitalTwin_InterfaceClient_SendTelemetryAsync failed for sending %s", telemetryName);
    }
    else
    {
        LogInfo("TEMPHUMIDSENSOR_INTERFACE:: DigitalTwin_InterfaceClient_SendTelemetryAsync successfully sent %s", telemetryName);
    }

    DigitalTwinClientHelper_Check();
    return result;
}

DIGITALTWIN_CLIENT_RESULT TempHumidSensorInterface_Telemetry_SendAll()
{
    DIGITALTWIN_CLIENT_RESULT result;

    // NOTE: Future versions of SDK will support ability to send multiple telemetries in a single
    // send.  For now, one at a time is sufficient albeit less efficient.
    if (((result = TempHumidSensorInterface_Telemetry_SendTemperature()) != DIGITALTWIN_CLIENT_OK) ||
        ((result = TempHumidSensorInterface_Telemetry_SendHumidity()) != DIGITALTWIN_CLIENT_OK) )

    {
        LogError("TEMPHUMIDSENSOR_INTERFACE: failed to send telemetries");
    }
    else
    {
        LogInfo("TEMPHUMIDSENSOR_INTERFACE: Queuing of all telemetries to be sent has succeeded");
    }

    return result;
}

DIGITALTWIN_CLIENT_RESULT TempHumidSensorInterface_Telemetry_SendTemperature()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("TEMPHUMIDSENSOR_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (TempHumidSensor_SerializeTemperatureTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return TempHumidSensorInterface_SendTelemetry_Internal(appState.interfaceClientHandle, TempHumidSensorInterface_TemperatureTelemetry, payloadBuffer);
    }
    else
    {
        LogError("TEMPHUMIDSENSOR_INTERFACE: serialize telemetry message temperature failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

DIGITALTWIN_CLIENT_RESULT TempHumidSensorInterface_Telemetry_SendHumidity()
{
    if (appState.interfaceClientHandle == NULL)
    {
        LogError("TEMPHUMIDSENSOR_INTERFACE: interfaceClientHandle is required to be initialized before sending telemetries");
    }

    char payloadBuffer[MAX_MASSAGE_SIZE];
    if (TempHumidSensor_SerializeHumidityTelemetry(payloadBuffer, MAX_MASSAGE_SIZE))
    {
        return TempHumidSensorInterface_SendTelemetry_Internal(appState.interfaceClientHandle, TempHumidSensorInterface_HumidityTelemetry, payloadBuffer);
    }
    else
    {
        LogError("TEMPHUMIDSENSOR_INTERFACE: serialize telemetry message humidity failed.");
        return DIGITALTWIN_CLIENT_ERROR;
    }
}

// TempHumidSensorInterface_InterfaceRegisteredCallback is invoked when this interface
// is successfully or unsuccessfully registered with the service, and also when the interface is deleted.
static void TempHumidSensorInterface_InterfaceRegisteredCallback(DIGITALTWIN_CLIENT_RESULT dtInterfaceStatus, void* userInterfaceContext)
{
    LogInfo("TempHumidSensorInterface_InterfaceRegisteredCallback with status=<%s>, userContext=<%p>", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus), userInterfaceContext);
    if (dtInterfaceStatus == DIGITALTWIN_CLIENT_OK)
    {
        // Once the interface is registered, send our reported properties to the service.  
        // It *IS* safe to invoke most DigitalTwin API calls from a callback thread like this, though it 
        // is NOT safe to create/destroy/register interfaces now.
        LogInfo("TEMPHUMIDSENSOR_INTERFACE: Interface successfully registered.");
    }
    else if (dtInterfaceStatus == DIGITALTWIN_CLIENT_ERROR_INTERFACE_UNREGISTERING)
    {
        // Once an interface is marked as unregistered, it cannot be used for any DigitalTwin SDK calls.
        LogInfo("TEMPHUMIDSENSOR_INTERFACE: Interface received unregistering callback.");
    }
    else
    {
        LogError("TEMPHUMIDSENSOR_INTERFACE: Interface received failed, status=<%s>.", MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, dtInterfaceStatus));
    }
}

//
// Create DigitalTwin interface client handle
//
DIGITALTWIN_INTERFACE_CLIENT_HANDLE TempHumidSensorInterface_Create()
{
    DIGITALTWIN_INTERFACE_CLIENT_HANDLE interfaceHandle;
    DIGITALTWIN_CLIENT_RESULT result;

    memset(&appState, 0, sizeof(TEMPHUMIDSENSOR_INTERFACE_STATE));

    if ((result = DigitalTwin_InterfaceClient_Create(TempHumidSensorInterfaceId,  TempHumidSensorInterfaceInstanceName, TempHumidSensorInterface_InterfaceRegisteredCallback, (void*)&appState, &interfaceHandle)) != DIGITALTWIN_CLIENT_OK)
    {
        LogError("TEMPHUMIDSENSOR_INTERFACE: Unable to allocate interface client handle for interfaceId=<%s>, interfaceInstanceName=<%s>, error=<%s>", TempHumidSensorInterfaceId, TempHumidSensorInterfaceInstanceName, MU_ENUM_TO_STRING(DIGITALTWIN_CLIENT_RESULT, result));
        interfaceHandle = NULL;
    }

    else
    {
        LogInfo("TEMPHUMIDSENSOR_INTERFACE: Created DIGITALTWIN_INTERFACE_CLIENT_HANDLE successfully for interfaceId=<%s>, interfaceInstanceName=<%s>, handle=<%p>", TempHumidSensorInterfaceId, TempHumidSensorInterfaceInstanceName, interfaceHandle);
        appState.interfaceClientHandle = interfaceHandle;
    }

    return interfaceHandle;
}

void TempHumidSensorInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle)
{
    // On shutdown, in general the first call made should be to DigitalTwin_InterfaceClient_Destroy.
    // This will block if there are any active callbacks in this interface, and then
    // mark the underlying handle such that no future callbacks shall come to it.
    DigitalTwin_InterfaceClient_Destroy(digitalTwinInterfaceClientHandle);

    // After DigitalTwin_InterfaceClient_Destroy returns, it is safe to assume
    // no more callbacks shall arrive for this interface and it is OK to free
    // resources callbacks otherwise may have needed.

}
