/************************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.1.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 *
 * Generated Date: Sunday, September 8, 2019
 ***********************************************************************************************/

#ifndef TEMPHUMIDSENSOR_INTERFACE_H
#define TEMPHUMIDSENSOR_INTERFACE_H

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include "digitaltwin_interface_client.h"
#include "azure_c_shared_utility/xlogging.h"
#include "azure_c_shared_utility/threadapi.h"

#include "digitaltwin_client_helper.h"
#include "digitaltwin_serializer.h"
#include "parson.h"
#include "../ReButton_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

typedef enum TEMPHUMIDSENSOR_TELEMETRY_TAG
{
    TempHumidSensor_TEMPERATURE_TELEMETRY,
    TempHumidSensor_HUMIDITY_TELEMETRY
} TEMPHUMIDSENSOR_TELEMETRY;

// DigitalTwin interface name from service perspective.
static const char TempHumidSensorInterfaceId[] = "urn:seeedkk:Interface:TempHumidSensor:1";
static const char TempHumidSensorInterfaceInstanceName[] = "TempHumidSensor";

// Telemetry names for this interface.

static const char TempHumidSensorInterface_TemperatureTelemetry[] = "temperature";

static const char TempHumidSensorInterface_HumidityTelemetry[] = "humidity";

// Property names for this interface.

// Command names for this interface

// Methods
DIGITALTWIN_INTERFACE_CLIENT_HANDLE TempHumidSensorInterface_Create();

void TempHumidSensorInterface_Close(DIGITALTWIN_INTERFACE_CLIENT_HANDLE digitalTwinInterfaceClientHandle);

DIGITALTWIN_CLIENT_RESULT TempHumidSensorInterface_Telemetry_SendTemperature();

DIGITALTWIN_CLIENT_RESULT TempHumidSensorInterface_Telemetry_SendHumidity();

DIGITALTWIN_CLIENT_RESULT TempHumidSensorInterface_Telemetry_SendAll();

#ifdef __cplusplus
}
#endif

#endif  // TEMPHUMIDSENSOR_INTERFACE_H
