/*********************************************************************************************
 * This code was automatically generated by Digital Twin Code Generator tool 0.6.1.
 *
 * Generated Date: 2019年9月2日
 *********************************************************************************************/

#ifndef PNP_DEVICE
#define PNP_DEVICE

#include "digitaltwin_device_client_ll.h"
#include "digitaltwin_interface_client.h"
#include "azure_c_shared_utility/threadapi.h"
#include "azure_c_shared_utility/tickcounter.h"
#include "utilities/digitaltwin_client_helper.h"

#include "utilities/deviceinfo_interface.h"

#include "utilities/battery_interface.h"

#include "utilities/pushbutton_interface.h"

#include "utilities/temphumidsensor_interface.h"

#include "ReButton_impl.h"

#ifdef __cplusplus
extern "C"
{
#endif

int pnp_device_initialize(const char* connectionString, const char* trustedCert);

void pnp_device_close();


//#define DEVICE_CAPABILITY_MODEL_URI "urn:seeedkk:ReButton:2"
#define DEVICE_CAPABILITY_MODEL_URI "urn:seeedkk:ReButtonTempHumidSensor:1"

#ifdef __cplusplus
}
#endif

#endif // PNP_DEVICE
